name: Install Docker on Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
      - name: Deploy
        uses: webfactory/ssh-agent@v0.5.0
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SERVER_IP }}
          server-port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.REMOTE_USERNAME }}
            
      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh
          sudo usermod -aG docker $USER

      - name: Verify Docker Installation
        run: |
          docker version
