name: Docker Compose Remote Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Update known_hosts
        run: ssh-keyscan your-remote-server >> ~/.ssh/known_hosts

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Deploy with Docker Compose
        run: |
          ssh ubuntu@43.204.38.88 'cd /path/to/project && docker-compose up -d'
