name: Install Docker on Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Update known_hosts
        run: ssh-keyscan your-remote-server >> ~/.ssh/known_hosts
      
      - name: Install Docker
        run: |
          ssh ubuntu@43.204.38.88 'curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh'
          ssh ubuntu@43.204.38.88 'sudo usermod -aG docker $USER'

      - name: Verify Docker Installation
        run: |
          ssh ubuntu@43.204.38.88 'docker version'
