name: Update APT on Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Update known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan 43.204.38.88 >> ~/.ssh/known_hosts

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run apt update
        run: |
          ssh ubuntu@43.204.38.88 'sudo apt update'
        
      - name: Install Java
        run: |
          ssh ubuntu@43.204.38.88 'sudo apt install default-jre -y'
          ssh ubuntu@43.204.38.88 'sudo apt install default-jdk -y'

      - name: Verify Java Installation
        run: |
          ssh ubuntu@43.204.38.88 'javac -version'

      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build and test
        run: |
          docker build -t myimg/your-app:latest .
          docker run myimg/your-app:latest npm test
    
     # - name: Tag Docker image
   #     run: docker tag my-app username/repo:latest
      
      - name: Build and Push Docker Image
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@43.204.38.88 'cd /path/to/app && docker build -t myimg/your-app:latest .'
          docker save myimg/your-app:latest | ssh -o StrictHostKeyChecking=no ubuntu@43.204.38.88 'docker load'

      - name: Push Docker image
        run: ssh ubuntu@43.204.38.88 'docker push username/repo:latest'
   #   - name: Build Docker image
   #   run: |
   #       ssh ubuntu@43.204.38.88 'docker build -t myimg .'

    #  - name: Run Docker container
     #   run: docker run -d mycont/your-app:latest
